# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 439aec7e4f33a1b5ad0983d69de45c99fcd6b515a52957814d153a1478f49c6f911727fd1f96877ef8952f26713db92762c3e5f7e1c7e99efb2963252629d9ee

test:
  secret_key_base: aa9ef2c50f5802ccfee23b272a04493bd9bf3640810a0867333ee35f87c31432abec2522b31610664813361420a7867be64777838ff1a2bca7fcd62378ba9417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
